### ISSUE TITLE
DOTween Utility Panel does not work!!!

### ISSUE THREAD

**Issue by EbiPenMan** [yoshida190/dotween#4]
![image](https://user-images.githubusercontent.com/7556608/131825345-41e3f9d3-7d45-4387-bf14-5ffa80f01ded.png)

![image](https://user-images.githubusercontent.com/7556608/131825605-389d180b-4001-44d9-b7bd-0b206ceffd60.png)

**Comment by yoshida190** [comment]
This error is difficult to deal with.

There is currently official discussion about packaging, so you should check that out.

**Comment by yoshida190** [comment]
https://github.com/yoshida190/dotween/issues/5
test
