### ISSUE TITLE
Fix license field

### ISSUE THREAD

**Issue by bassarisse** [yoshida190/dotween#5]
Due to https://github.com/openupm/openupm/issues/3153, apparently the package is not available on OpenUPM anymore.

How can we fix this? Just adding the license? I guess this would require a version bump, but it would de-sync with the original repo, right?

**Comment by Cardidi** [comment]
I've met same situation as you

**Comment by yoshida190** [comment]
Currently, there is official discussion about upm.

https://github.com/Demigiant/dotween/issues/251
Please check the URL of.

There is also a reference to the license
